name: mate-support-stack-cuda
services:

  ollama-llm:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
     - ollama-downloads:/root/.ollama
     - ./llm/ollama-entrypoint.sh:/entrypoint.sh
    container_name: ollama-llm
    pull_policy: always
    tty: true
    restart: always
    environment:
     - OLLAMA_KEEP_ALIVE=24h
     - OLLAMA_HOST=0.0.0.0
     - OLLAMA_MODELS=/root/.ollama/models
     - OLLAMA_MODEL_DL=llama3.2:3b,llama3.1:8b
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tts-server:
    image: ghcr.io/matatonic/openedai-speech-min
    ports:
      - "8001:8000"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    environment:
      TTS_HOME: "/app/voices"
      HF_HOME: "/app/voices"
      PRELOAD_MODEL: "tts_models/de/thorsten/vits"
      LANGUAGE: "de_DE"
      VOICE: "thorsten-medium"
      PIPER_VOICE: "thorsten-medium"
    command: ['python', 'speech.py', '--xtts_device', 'none']
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"

#
# available env vars, see:
# https://github.com/fedirz/faster-whisper-server/blob/master/src/faster_whisper_server/config.py
#
  faster-whisper-server:
    image: fedirz/faster-whisper-server:latest-cuda
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    environment:
      - WHISPER__MODEL=Systran/faster-whisper-large-v3
      #- WHISPER__MODEL=Systran/faster-whisper-medium
      - WHISPER__COMPUTE_TYPE=int8
      - DEFAULT_LANGUAGE=de
#      - UVICORN_HOST=0.0.0.0
#      - UVICORN_PORT=8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              # If you have CDI feature enabled use the following instead
              # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html
              # https://docs.docker.com/reference/cli/dockerd/#enable-cdi-devices
              # - driver: cdi
              #   device_ids:
              #   - nvidia.com/gpu=all

volumes:
  ollama-downloads:
  hugging_face_cache:
